# Configuration for oapi-codegen
package: client
generate:
  models: true
  client: true
  chi-server: false
  echo-server: false
output: client/generated.go
output-options:
  skip-prune: true
import-mapping:
  "": "github.com/Oway-Inc/oway-sdk/packages/go/client"
