// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyScopes     = "apiKey.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ShipmentOrderStatus.
const (
	ShipmentOrderStatusACCEPTED    ShipmentOrderStatus = "ACCEPTED"
	ShipmentOrderStatusASSIGNED    ShipmentOrderStatus = "ASSIGNED"
	ShipmentOrderStatusCANCELLED   ShipmentOrderStatus = "CANCELLED"
	ShipmentOrderStatusCONFIRMED   ShipmentOrderStatus = "CONFIRMED"
	ShipmentOrderStatusDELIVERED   ShipmentOrderStatus = "DELIVERED"
	ShipmentOrderStatusINITIALIZED ShipmentOrderStatus = "INITIALIZED"
	ShipmentOrderStatusINTRANSIT   ShipmentOrderStatus = "IN_TRANSIT"
	ShipmentOrderStatusPICKEDUP    ShipmentOrderStatus = "PICKED_UP"
)

// Defines values for TrackingOrderStatus.
const (
	TrackingOrderStatusACCEPTED    TrackingOrderStatus = "ACCEPTED"
	TrackingOrderStatusASSIGNED    TrackingOrderStatus = "ASSIGNED"
	TrackingOrderStatusCANCELLED   TrackingOrderStatus = "CANCELLED"
	TrackingOrderStatusCONFIRMED   TrackingOrderStatus = "CONFIRMED"
	TrackingOrderStatusDELIVERED   TrackingOrderStatus = "DELIVERED"
	TrackingOrderStatusINITIALIZED TrackingOrderStatus = "INITIALIZED"
	TrackingOrderStatusINTRANSIT   TrackingOrderStatus = "IN_TRANSIT"
	TrackingOrderStatusPICKEDUP    TrackingOrderStatus = "PICKED_UP"
)

// Defines values for GetDocumentByOrderNumberParamsDocumentType.
const (
	BILLOFLADING  GetDocumentByOrderNumberParamsDocumentType = "BILL_OF_LADING"
	INVOICE       GetDocumentByOrderNumberParamsDocumentType = "INVOICE"
	SHIPPINGLABEL GetDocumentByOrderNumberParamsDocumentType = "SHIPPING_LABEL"
)

// Address Address information for pickup or delivery locations
type Address struct {
	// Address1 Primary street address
	Address1 string `json:"address1"`

	// Address2 Secondary address line (suite, unit, etc.)
	Address2 *string `json:"address2,omitempty"`

	// AppointmentRequired Whether an appointment is required for pickup/delivery
	AppointmentRequired *bool `json:"appointmentRequired,omitempty"`

	// City City name
	City string `json:"city"`

	// CloseTime Closing time for the location in 24-hour format (HH:mm). Defaults to 16:00 if not provided.
	CloseTime *string `json:"closeTime,omitempty"`

	// ContactPerson Name of the contact person at this location
	ContactPerson string `json:"contactPerson"`

	// LiftgateRequired Whether a liftgate is required at this location
	LiftgateRequired *bool `json:"liftgateRequired,omitempty"`

	// LimitedAccess Whether this is a limited access location (residential, construction site, etc.)
	LimitedAccess *bool `json:"limitedAccess,omitempty"`

	// Name Name of the location or business
	Name string `json:"name"`

	// Notes Additional notes or instructions for the driver
	Notes *string `json:"notes,omitempty"`

	// OpenTime Opening time for the location in 24-hour format (HH:mm). Defaults to 10:00 if not provided.
	OpenTime *string `json:"openTime,omitempty"`

	// PhoneNumber Contact phone number in E.164 format
	PhoneNumber string `json:"phoneNumber"`

	// State Two-letter state abbreviation
	State string `json:"state"`

	// ZipCode 5-digit ZIP code
	ZipCode string `json:"zipCode"`
}

// CreateShipmentRequest Request to create a new shipment
type CreateShipmentRequest struct {
	// DeliveryAddress Address information for pickup or delivery locations
	DeliveryAddress Address `json:"deliveryAddress"`

	// Description Description of the shipment contents
	Description string `json:"description"`

	// OrderComponents List of cargo components in the shipment
	OrderComponents []OrderComponent `json:"orderComponents"`

	// PickupAddress Address information for pickup or delivery locations
	PickupAddress Address `json:"pickupAddress"`

	// PoNumber Purchase order number for reference
	PoNumber *string `json:"poNumber,omitempty"`

	// QuoteId Optional ID of a previously generated quote. If provided, the shipment must match the quote parameters.
	QuoteId *string `json:"quoteId,omitempty"`

	// RefNumber Additional reference number
	RefNumber *string `json:"refNumber,omitempty"`

	// RequiredDeliveryBy Required delivery by date (ISO 8601 format)
	RequiredDeliveryBy *time.Time `json:"requiredDeliveryBy,omitempty"`

	// RequiredPickupDate Required pickup date (ISO 8601 format)
	RequiredPickupDate *time.Time `json:"requiredPickupDate,omitempty"`
}

// DocumentResponse Response containing document download information
type DocumentResponse struct {
	// DownloadLink Pre-signed URL to download the document. Link expires after a short time.
	DownloadLink *string `json:"downloadLink,omitempty"`

	// FileType MIME type of the document
	FileType *string `json:"fileType,omitempty"`

	// Filename Name of the document file
	Filename *string `json:"filename,omitempty"`
}

// InvoiceCharge An individual charge/fee on the invoice
type InvoiceCharge struct {
	// AmountInCents Charge amount in cents (USD)
	AmountInCents *int32 `json:"amountInCents,omitempty"`

	// ChargeType Type of charge (e.g., BASE_FREIGHT, LIFTGATE_PICKUP, LIFTGATE_DELIVERY)
	ChargeType *string `json:"chargeType,omitempty"`

	// Description Human-readable description of the charge
	Description *string `json:"description,omitempty"`
}

// InvoiceLineItem A line item on the invoice representing shipped goods
type InvoiceLineItem struct {
	// Description Description of the goods
	Description *string `json:"description,omitempty"`

	// FreightClass Freight class (NMFC)
	FreightClass *string `json:"freightClass,omitempty"`

	// PackageType Type of packaging (e.g., PLT for pallet, CTN for carton)
	PackageType *string `json:"packageType,omitempty"`

	// Quantity Number of pieces/pallets
	Quantity *int32 `json:"quantity,omitempty"`

	// Weight Weight in pounds
	Weight *int32 `json:"weight,omitempty"`
}

// InvoiceResponse Itemized invoice for a delivered shipment
type InvoiceResponse struct {
	// BillTo Address information for pickup or delivery locations
	BillTo *Address `json:"billTo,omitempty"`

	// Charges Itemized charges and fees
	Charges *[]InvoiceCharge `json:"charges,omitempty"`

	// Consignee Address information for pickup or delivery locations
	Consignee *Address `json:"consignee,omitempty"`

	// DeliveryDate Delivery date (when the shipment was delivered)
	DeliveryDate *time.Time `json:"deliveryDate,omitempty"`

	// InvoiceDate Invoice date (when the shipment was delivered)
	InvoiceDate *time.Time `json:"invoiceDate,omitempty"`

	// LineItems Line items representing the shipped goods
	LineItems *[]InvoiceLineItem `json:"lineItems,omitempty"`

	// OrderId Unique identifier for the order
	OrderId *string `json:"orderId,omitempty"`

	// OrderNumber Order number (PRO number)
	OrderNumber *string `json:"orderNumber,omitempty"`

	// PoNumber Purchase order number (if provided)
	PoNumber *string `json:"poNumber,omitempty"`

	// RefNumber Reference number (BOL number)
	RefNumber *string `json:"refNumber,omitempty"`

	// ShipDate Ship date (when the shipment was picked up)
	ShipDate *time.Time `json:"shipDate,omitempty"`

	// Shipper Address information for pickup or delivery locations
	Shipper *Address `json:"shipper,omitempty"`

	// TotalChargesInCents Total of all charges in cents (USD)
	TotalChargesInCents *int32 `json:"totalChargesInCents,omitempty"`

	// TotalPieces Total number of pieces/pallets
	TotalPieces *int32 `json:"totalPieces,omitempty"`

	// TotalWeight Total weight of the shipment in pounds
	TotalWeight *int32 `json:"totalWeight,omitempty"`
}

// OrderComponent Individual cargo component in a shipment.
//
// **Validation Rules:**
// - Total weight across all components must equal order totalPoundsWeight
// - Total pallet count across all components must equal order totalPalletCount
// - Weight must be between 1 and 2,500 lbs per pallet
// - Dimensions must be within limits (see palletDimensions field)
type OrderComponent struct {
	// PalletCount Number of pallets for this component
	PalletCount int32 `json:"palletCount"`

	// PalletDimensions Pallet dimensions in inches as [length, width, height].
	//
	// **Dimension Limits:**
	// - Standard shipments: max 95×95×94 inches
	// - With liftgate accessorial: max 62×62×94 inches
	// - Oversize rule: Both length AND width cannot exceed 60 inches
	// - Minimum: 1×1×1 inches
	PalletDimensions []int32 `json:"palletDimensions"`

	// PoundsWeight Total weight for this component in pounds. Must be between 1 and 2,500 lbs per pallet (e.g., 2 pallets = max 5,000 lbs).
	PoundsWeight float64 `json:"poundsWeight"`
}

// QuoteRequest Request to generate a shipping quote. Quotes are valid for 2 days from creation.
type QuoteRequest struct {
	// DeliveryAddress Address information for pickup or delivery locations
	DeliveryAddress Address `json:"deliveryAddress"`

	// OrderComponents List of pallets or freight pieces. Quote will be based on total pallet count and weight.
	OrderComponents []OrderComponent `json:"orderComponents"`

	// PickupAddress Address information for pickup or delivery locations
	PickupAddress Address `json:"pickupAddress"`
}

// QuoteResponse Response containing quote details
type QuoteResponse struct {
	// Id Unique identifier for the quote
	Id *string `json:"id,omitempty"`

	// QuoteExpirationTime Time when the quote expires (ISO 8601 format). Quotes are valid for 2 days.
	QuoteExpirationTime *time.Time `json:"quoteExpirationTime,omitempty"`

	// QuotedPriceInCents Total quoted price in cents (USD)
	QuotedPriceInCents *int32 `json:"quotedPriceInCents,omitempty"`
}

// Shipment Shipment/Order details
type Shipment struct {
	// CompanyId Company ID that owns this order
	CompanyId *string `json:"companyId,omitempty"`

	// CreatedAt Time when the order was created (ISO 8601 format)
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Id Unique identifier for the order
	Id *string `json:"id,omitempty"`

	// OrderNumber Human-readable PRO number for the shipment (5-character alphanumeric)
	OrderNumber *string `json:"orderNumber,omitempty"`

	// OrderStatus Current status of the order
	OrderStatus *ShipmentOrderStatus `json:"orderStatus,omitempty"`

	// TotalPriceInCents Total price of the order in cents (USD)
	TotalPriceInCents *int32 `json:"totalPriceInCents,omitempty"`

	// UpdatedAt Time when the order was last updated (ISO 8601 format)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// UserId User ID who created this order
	UserId *string `json:"userId,omitempty"`
}

// ShipmentOrderStatus Current status of the order
type ShipmentOrderStatus string

// Tracking Shipment tracking information
type Tracking struct {
	// ActualDeliveryDate Actual delivery date/time (ISO 8601 format)
	ActualDeliveryDate *time.Time `json:"actualDeliveryDate,omitempty"`

	// ActualPickupDate Actual pickup date/time (ISO 8601 format)
	ActualPickupDate *time.Time `json:"actualPickupDate,omitempty"`

	// EstimatedDeliveryDate Estimated delivery date/time (ISO 8601 format)
	EstimatedDeliveryDate *time.Time `json:"estimatedDeliveryDate,omitempty"`

	// EstimatedPickupDate Estimated pickup date/time (ISO 8601 format)
	EstimatedPickupDate *time.Time `json:"estimatedPickupDate,omitempty"`

	// Id Unique identifier for the order
	Id *string `json:"id,omitempty"`

	// OrderNumber Human-readable PRO number for the shipment (5-character alphanumeric)
	OrderNumber *string `json:"orderNumber,omitempty"`

	// OrderStatus Current status of the order
	OrderStatus *TrackingOrderStatus `json:"orderStatus,omitempty"`
}

// TrackingOrderStatus Current status of the order
type TrackingOrderStatus string

// GetDocumentByOrderNumberParamsDocumentType defines parameters for GetDocumentByOrderNumber.
type GetDocumentByOrderNumberParamsDocumentType string

// RequestQuoteJSONRequestBody defines body for RequestQuote for application/json ContentType.
type RequestQuoteJSONRequestBody = QuoteRequest

// CreateShipmentJSONRequestBody defines body for CreateShipment for application/json ContentType.
type CreateShipmentJSONRequestBody = CreateShipmentRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RequestQuoteWithBody request with any body
	RequestQuoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RequestQuote(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetQuote request
	GetQuote(ctx context.Context, quoteId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateShipmentWithBody request with any body
	CreateShipmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateShipment(ctx context.Context, body CreateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetShipmentByOrderNumber request
	GetShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelShipmentByOrderNumber request
	CancelShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfirmShipmentByOrderNumber request
	ConfirmShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDocumentByOrderNumber request
	GetDocumentByOrderNumber(ctx context.Context, orderNumber string, documentType GetDocumentByOrderNumberParamsDocumentType, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInvoice request
	GetInvoice(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TrackShipmentByOrderNumber request
	TrackShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RequestQuoteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestQuoteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RequestQuote(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestQuoteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetQuote(ctx context.Context, quoteId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQuoteRequest(c.Server, quoteId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateShipmentWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateShipmentRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateShipment(ctx context.Context, body CreateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateShipmentRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetShipmentByOrderNumberRequest(c.Server, orderNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelShipmentByOrderNumberRequest(c.Server, orderNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConfirmShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmShipmentByOrderNumberRequest(c.Server, orderNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDocumentByOrderNumber(ctx context.Context, orderNumber string, documentType GetDocumentByOrderNumberParamsDocumentType, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDocumentByOrderNumberRequest(c.Server, orderNumber, documentType)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInvoice(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInvoiceRequest(c.Server, orderNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TrackShipmentByOrderNumber(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTrackShipmentByOrderNumberRequest(c.Server, orderNumber)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRequestQuoteRequest calls the generic RequestQuote builder with application/json body
func NewRequestQuoteRequest(server string, body RequestQuoteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRequestQuoteRequestWithBody(server, "application/json", bodyReader)
}

// NewRequestQuoteRequestWithBody generates requests for RequestQuote with any type of body
func NewRequestQuoteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/quote")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetQuoteRequest generates requests for GetQuote
func NewGetQuoteRequest(server string, quoteId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "quoteId", runtime.ParamLocationPath, quoteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/quote/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateShipmentRequest calls the generic CreateShipment builder with application/json body
func NewCreateShipmentRequest(server string, body CreateShipmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateShipmentRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateShipmentRequestWithBody generates requests for CreateShipment with any type of body
func NewCreateShipmentRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetShipmentByOrderNumberRequest generates requests for GetShipmentByOrderNumber
func NewGetShipmentByOrderNumberRequest(server string, orderNumber string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orderNumber", runtime.ParamLocationPath, orderNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCancelShipmentByOrderNumberRequest generates requests for CancelShipmentByOrderNumber
func NewCancelShipmentByOrderNumberRequest(server string, orderNumber string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orderNumber", runtime.ParamLocationPath, orderNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment/%s/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewConfirmShipmentByOrderNumberRequest generates requests for ConfirmShipmentByOrderNumber
func NewConfirmShipmentByOrderNumberRequest(server string, orderNumber string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orderNumber", runtime.ParamLocationPath, orderNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment/%s/confirm", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDocumentByOrderNumberRequest generates requests for GetDocumentByOrderNumber
func NewGetDocumentByOrderNumberRequest(server string, orderNumber string, documentType GetDocumentByOrderNumberParamsDocumentType) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orderNumber", runtime.ParamLocationPath, orderNumber)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "documentType", runtime.ParamLocationPath, documentType)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment/%s/document/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInvoiceRequest generates requests for GetInvoice
func NewGetInvoiceRequest(server string, orderNumber string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orderNumber", runtime.ParamLocationPath, orderNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment/%s/invoice", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTrackShipmentByOrderNumberRequest generates requests for TrackShipmentByOrderNumber
func NewTrackShipmentByOrderNumberRequest(server string, orderNumber string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orderNumber", runtime.ParamLocationPath, orderNumber)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/shipper/shipment/%s/tracking", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RequestQuoteWithBodyWithResponse request with any body
	RequestQuoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error)

	RequestQuoteWithResponse(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error)

	// GetQuoteWithResponse request
	GetQuoteWithResponse(ctx context.Context, quoteId string, reqEditors ...RequestEditorFn) (*GetQuoteResponse, error)

	// CreateShipmentWithBodyWithResponse request with any body
	CreateShipmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateShipmentResponse, error)

	CreateShipmentWithResponse(ctx context.Context, body CreateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateShipmentResponse, error)

	// GetShipmentByOrderNumberWithResponse request
	GetShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*GetShipmentByOrderNumberResponse, error)

	// CancelShipmentByOrderNumberWithResponse request
	CancelShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*CancelShipmentByOrderNumberResponse, error)

	// ConfirmShipmentByOrderNumberWithResponse request
	ConfirmShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*ConfirmShipmentByOrderNumberResponse, error)

	// GetDocumentByOrderNumberWithResponse request
	GetDocumentByOrderNumberWithResponse(ctx context.Context, orderNumber string, documentType GetDocumentByOrderNumberParamsDocumentType, reqEditors ...RequestEditorFn) (*GetDocumentByOrderNumberResponse, error)

	// GetInvoiceWithResponse request
	GetInvoiceWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*GetInvoiceResponse, error)

	// TrackShipmentByOrderNumberWithResponse request
	TrackShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*TrackShipmentByOrderNumberResponse, error)
}

type RequestQuoteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *QuoteResponse
	HALJSON400   *QuoteResponse
	HALJSON401   *QuoteResponse
	HALJSON403   *QuoteResponse
	HALJSON500   *QuoteResponse
}

// Status returns HTTPResponse.Status
func (r RequestQuoteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RequestQuoteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetQuoteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *QuoteResponse
	HALJSON400   *QuoteResponse
	HALJSON401   *QuoteResponse
	HALJSON403   *QuoteResponse
	HALJSON404   *QuoteResponse
}

// Status returns HTTPResponse.Status
func (r GetQuoteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetQuoteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateShipmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *Shipment
	HALJSON400   *Shipment
	HALJSON401   *Shipment
	HALJSON403   *Shipment
	HALJSON500   *Shipment
}

// Status returns HTTPResponse.Status
func (r CreateShipmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateShipmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetShipmentByOrderNumberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *Shipment
	HALJSON400   *Shipment
	HALJSON401   *Shipment
	HALJSON403   *Shipment
	HALJSON404   *Shipment
}

// Status returns HTTPResponse.Status
func (r GetShipmentByOrderNumberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetShipmentByOrderNumberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CancelShipmentByOrderNumberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *Shipment
	HALJSON400   *Shipment
	HALJSON401   *Shipment
	HALJSON403   *Shipment
	HALJSON404   *Shipment
	HALJSON500   *Shipment
}

// Status returns HTTPResponse.Status
func (r CancelShipmentByOrderNumberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelShipmentByOrderNumberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConfirmShipmentByOrderNumberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *Shipment
	HALJSON400   *Shipment
	HALJSON401   *Shipment
	HALJSON403   *Shipment
	HALJSON404   *Shipment
	HALJSON500   *Shipment
}

// Status returns HTTPResponse.Status
func (r ConfirmShipmentByOrderNumberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfirmShipmentByOrderNumberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDocumentByOrderNumberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *DocumentResponse
	HALJSON400   *DocumentResponse
	HALJSON401   *DocumentResponse
	HALJSON403   *DocumentResponse
	HALJSON404   *DocumentResponse
	HALJSON500   *DocumentResponse
}

// Status returns HTTPResponse.Status
func (r GetDocumentByOrderNumberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDocumentByOrderNumberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInvoiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *InvoiceResponse
	HALJSON400   *InvoiceResponse
	HALJSON401   *InvoiceResponse
	HALJSON403   *InvoiceResponse
	HALJSON404   *InvoiceResponse
}

// Status returns HTTPResponse.Status
func (r GetInvoiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInvoiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TrackShipmentByOrderNumberResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	HALJSON200   *Tracking
	HALJSON400   *Tracking
	HALJSON401   *Tracking
	HALJSON403   *Tracking
	HALJSON404   *Tracking
}

// Status returns HTTPResponse.Status
func (r TrackShipmentByOrderNumberResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TrackShipmentByOrderNumberResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RequestQuoteWithBodyWithResponse request with arbitrary body returning *RequestQuoteResponse
func (c *ClientWithResponses) RequestQuoteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error) {
	rsp, err := c.RequestQuoteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestQuoteResponse(rsp)
}

func (c *ClientWithResponses) RequestQuoteWithResponse(ctx context.Context, body RequestQuoteJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestQuoteResponse, error) {
	rsp, err := c.RequestQuote(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestQuoteResponse(rsp)
}

// GetQuoteWithResponse request returning *GetQuoteResponse
func (c *ClientWithResponses) GetQuoteWithResponse(ctx context.Context, quoteId string, reqEditors ...RequestEditorFn) (*GetQuoteResponse, error) {
	rsp, err := c.GetQuote(ctx, quoteId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetQuoteResponse(rsp)
}

// CreateShipmentWithBodyWithResponse request with arbitrary body returning *CreateShipmentResponse
func (c *ClientWithResponses) CreateShipmentWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateShipmentResponse, error) {
	rsp, err := c.CreateShipmentWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateShipmentResponse(rsp)
}

func (c *ClientWithResponses) CreateShipmentWithResponse(ctx context.Context, body CreateShipmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateShipmentResponse, error) {
	rsp, err := c.CreateShipment(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateShipmentResponse(rsp)
}

// GetShipmentByOrderNumberWithResponse request returning *GetShipmentByOrderNumberResponse
func (c *ClientWithResponses) GetShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*GetShipmentByOrderNumberResponse, error) {
	rsp, err := c.GetShipmentByOrderNumber(ctx, orderNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetShipmentByOrderNumberResponse(rsp)
}

// CancelShipmentByOrderNumberWithResponse request returning *CancelShipmentByOrderNumberResponse
func (c *ClientWithResponses) CancelShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*CancelShipmentByOrderNumberResponse, error) {
	rsp, err := c.CancelShipmentByOrderNumber(ctx, orderNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelShipmentByOrderNumberResponse(rsp)
}

// ConfirmShipmentByOrderNumberWithResponse request returning *ConfirmShipmentByOrderNumberResponse
func (c *ClientWithResponses) ConfirmShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*ConfirmShipmentByOrderNumberResponse, error) {
	rsp, err := c.ConfirmShipmentByOrderNumber(ctx, orderNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmShipmentByOrderNumberResponse(rsp)
}

// GetDocumentByOrderNumberWithResponse request returning *GetDocumentByOrderNumberResponse
func (c *ClientWithResponses) GetDocumentByOrderNumberWithResponse(ctx context.Context, orderNumber string, documentType GetDocumentByOrderNumberParamsDocumentType, reqEditors ...RequestEditorFn) (*GetDocumentByOrderNumberResponse, error) {
	rsp, err := c.GetDocumentByOrderNumber(ctx, orderNumber, documentType, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDocumentByOrderNumberResponse(rsp)
}

// GetInvoiceWithResponse request returning *GetInvoiceResponse
func (c *ClientWithResponses) GetInvoiceWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*GetInvoiceResponse, error) {
	rsp, err := c.GetInvoice(ctx, orderNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInvoiceResponse(rsp)
}

// TrackShipmentByOrderNumberWithResponse request returning *TrackShipmentByOrderNumberResponse
func (c *ClientWithResponses) TrackShipmentByOrderNumberWithResponse(ctx context.Context, orderNumber string, reqEditors ...RequestEditorFn) (*TrackShipmentByOrderNumberResponse, error) {
	rsp, err := c.TrackShipmentByOrderNumber(ctx, orderNumber, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTrackShipmentByOrderNumberResponse(rsp)
}

// ParseRequestQuoteResponse parses an HTTP response from a RequestQuoteWithResponse call
func ParseRequestQuoteResponse(rsp *http.Response) (*RequestQuoteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RequestQuoteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON500 = &dest

	}

	return response, nil
}

// ParseGetQuoteResponse parses an HTTP response from a GetQuoteWithResponse call
func ParseGetQuoteResponse(rsp *http.Response) (*GetQuoteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetQuoteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest QuoteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	}

	return response, nil
}

// ParseCreateShipmentResponse parses an HTTP response from a CreateShipmentWithResponse call
func ParseCreateShipmentResponse(rsp *http.Response) (*CreateShipmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateShipmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON500 = &dest

	}

	return response, nil
}

// ParseGetShipmentByOrderNumberResponse parses an HTTP response from a GetShipmentByOrderNumberWithResponse call
func ParseGetShipmentByOrderNumberResponse(rsp *http.Response) (*GetShipmentByOrderNumberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetShipmentByOrderNumberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	}

	return response, nil
}

// ParseCancelShipmentByOrderNumberResponse parses an HTTP response from a CancelShipmentByOrderNumberWithResponse call
func ParseCancelShipmentByOrderNumberResponse(rsp *http.Response) (*CancelShipmentByOrderNumberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelShipmentByOrderNumberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON500 = &dest

	}

	return response, nil
}

// ParseConfirmShipmentByOrderNumberResponse parses an HTTP response from a ConfirmShipmentByOrderNumberWithResponse call
func ParseConfirmShipmentByOrderNumberResponse(rsp *http.Response) (*ConfirmShipmentByOrderNumberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfirmShipmentByOrderNumberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Shipment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON500 = &dest

	}

	return response, nil
}

// ParseGetDocumentByOrderNumberResponse parses an HTTP response from a GetDocumentByOrderNumberWithResponse call
func ParseGetDocumentByOrderNumberResponse(rsp *http.Response) (*GetDocumentByOrderNumberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDocumentByOrderNumberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest DocumentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON500 = &dest

	}

	return response, nil
}

// ParseGetInvoiceResponse parses an HTTP response from a GetInvoiceWithResponse call
func ParseGetInvoiceResponse(rsp *http.Response) (*GetInvoiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInvoiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InvoiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest InvoiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest InvoiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest InvoiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest InvoiceResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	}

	return response, nil
}

// ParseTrackShipmentByOrderNumberResponse parses an HTTP response from a TrackShipmentByOrderNumberWithResponse call
func ParseTrackShipmentByOrderNumberResponse(rsp *http.Response) (*TrackShipmentByOrderNumberResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TrackShipmentByOrderNumberResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Tracking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Tracking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Tracking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Tracking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Tracking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.HALJSON404 = &dest

	}

	return response, nil
}
