// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddData implements addData operation.
//
// Submit GPS location data for carrier vehicles. Each data point must include vehicle ID,
// coordinates, timestamp, heading, and speed.
//
// POST /v1/carrier/{carrierId}/gps-data
func (UnimplementedHandler) AddData(ctx context.Context, req []GpsData, params AddDataParams) (r AddDataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddTrips implements addTrips operation.
//
// Submit trip data for carrier vehicles. Each trip must include vehicle ID, trip number, and legs
// with start/end coordinates and arrival windows.
//
// POST /v1/carrier/{carrierId}/trips
func (UnimplementedHandler) AddTrips(ctx context.Context, req []Trip, params AddTripsParams) (r AddTripsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelShipmentByOrderNumber implements cancelShipmentByOrderNumber operation.
//
// Cancels an existing shipment using its order number (PRO number). Shipments can only be cancelled
// when they are in a cancellable state (e.g., before pickup).
//
// PUT /v1/shipper/shipment/{orderNumber}/cancel
func (UnimplementedHandler) CancelShipmentByOrderNumber(ctx context.Context, params CancelShipmentByOrderNumberParams) (r CancelShipmentByOrderNumberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConfirmShipmentByOrderNumber implements confirmShipmentByOrderNumber operation.
//
// Confirms an existing shipment using its order number (PRO number).
// Moves the shipment from INITIALIZED to CONFIRMED state.
// **Prerequisites:**
// - The order must be in INITIALIZED state
// - The order must have an associated quote
// **Validation Requirements:**
// The following fields are validated during confirmation. If any are missing or invalid,
// the shipment will remain in INITIALIZED state.
// *Address Fields (required on BOTH pickup and delivery addresses):*
// - `name` - Location/company name
// - `address1` - Street address
// - `zipCode` - ZIP code
// - `contactPerson` - Contact name
// - `phoneNumber` - Contact phone (E.164 format, e.g., "+15551234567")
// - `openTime` - Opening time in HH:mm format (defaults to "10:00")
// - `closeTime` - Closing time in HH:mm format (defaults to "16:00")
// *Order Fields:*
// - `description` - Must not be empty
// - `totalPalletCount` - Must be between 1 and 51
// - `totalPoundsWeight` - Must be between 1 and 2,500 lbs per pallet
// *Order Component Fields (per component):*
// - `palletCount` - Must be at least 1
// - `poundsWeight` - Must be between 1 and 2,500 lbs per pallet
// - `palletDimensions` - Must be valid dimensions within limits (subject to change, these are
// configurable):
// - Standard: max 60×52×94 inches (L×W×H) - pallets exceeding these are charged as oversized
// - Oversized maximum: 95×95×96 inches - no pallet can exceed this
// - With liftgate: max 62×62×94 inches
// *Component Totals:*
// - Sum of component `palletCount` must equal order `totalPalletCount`
// - Sum of component `poundsWeight` must equal order `totalPoundsWeight`.
//
// PUT /v1/shipper/shipment/{orderNumber}/confirm
func (UnimplementedHandler) ConfirmShipmentByOrderNumber(ctx context.Context, params ConfirmShipmentByOrderNumberParams) (r ConfirmShipmentByOrderNumberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateShipment implements createShipment operation.
//
// Creates a new shipment order. Optionally reference a previously generated quote. The shipment must
// be confirmed after creation.
// **Note:** The `companyId` is automatically extracted from your API key.
// You do not need to provide this value in the request body.
// For M2M (machine-to-machine) integrations, no user context is required.
//
// POST /v1/shipper/shipment
func (UnimplementedHandler) CreateShipment(ctx context.Context, req *ExternalCreateShipmentRequest) (r CreateShipmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCarrierApiConfig implements getCarrierApiConfig operation.
//
// Retrieves the API configuration for a carrier including company name, API version, and available
// endpoints.
//
// GET /v1/carrier/{carrierId}
func (UnimplementedHandler) GetCarrierApiConfig(ctx context.Context, params GetCarrierApiConfigParams) (r GetCarrierApiConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDocumentByOrderNumber implements getDocumentByOrderNumber operation.
//
// Retrieves a download link for a shipment document using the order number (PRO number). Supported
// document types: BILL_OF_LADING, INVOICE, SHIPPING_LABEL.
//
// GET /v1/shipper/shipment/{orderNumber}/document/{documentType}
func (UnimplementedHandler) GetDocumentByOrderNumber(ctx context.Context, params GetDocumentByOrderNumberParams) (r GetDocumentByOrderNumberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInvoice implements getInvoice operation.
//
// Retrieves the itemized invoice for a delivered shipment.
// The invoice includes all charges (base freight, accessorials) and line items.
// **Note:** This endpoint is only available for shipments in DELIVERED state.
// Invoices are finalized when a shipment is delivered.
//
// GET /v1/shipper/shipment/{orderNumber}/invoice
func (UnimplementedHandler) GetInvoice(ctx context.Context, params GetInvoiceParams) (r GetInvoiceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetJobs implements getJobs operation.
//
// Retrieves jobs (offers with order data) for a carrier. Filter by active status and time range.
//
// GET /v1/carrier/{carrierId}/jobs
func (UnimplementedHandler) GetJobs(ctx context.Context, params GetJobsParams) (r GetJobsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetQuote implements getQuote operation.
//
// Retrieves an existing quote by its unique identifier. Quotes are valid for 2 days from creation.
//
// GET /v1/shipper/quote/{quoteId}
func (UnimplementedHandler) GetQuote(ctx context.Context, params GetQuoteParams) (r GetQuoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetShipmentByOrderNumber implements getShipmentByOrderNumber operation.
//
// Retrieves a shipment by its order number (PRO number). The order number is a 5-character
// alphanumeric code (e.g., ZKYQ5) that uniquely identifies the shipment.
//
// GET /v1/shipper/shipment/{orderNumber}
func (UnimplementedHandler) GetShipmentByOrderNumber(ctx context.Context, params GetShipmentByOrderNumberParams) (r GetShipmentByOrderNumberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetToken implements getToken operation.
//
// Exchange client credentials for an access token.
// The returned token includes scopes that determine API access:
// - `shipper` scope grants access to `/v1/shipper/**` endpoints
// - `carrier` scope grants access to `/v1/carrier/**` endpoints
// - Partners with both scopes can access both APIs with a single token
// The returned token should be included in subsequent API requests as a Bearer token
// in the authorization header: `authorization: Bearer {access_token}`
// Tokens are valid for the duration specified in `expires_in` (seconds).
// We recommend caching tokens and refreshing them before expiration.
//
// POST /v1/auth/token
func (UnimplementedHandler) GetToken(ctx context.Context, req *TokenRequest) (r GetTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RequestQuote implements requestQuote operation.
//
// Generates a price quote for a shipment based on origin, destination, and cargo details. The quote
// is valid for 2 days.
// **Note:** The `companyId` is automatically extracted from your API key.
// You do not need to provide this value in the request body.
// For M2M (machine-to-machine) integrations, no user context is required.
//
// POST /v1/shipper/quote
func (UnimplementedHandler) RequestQuote(ctx context.Context, req *ExternalRequestQuoteRequest) (r RequestQuoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TrackShipmentByOrderNumber implements trackShipmentByOrderNumber operation.
//
// Retrieves tracking information for a shipment by its order number (PRO number). Returns status and
// estimated/actual pickup and delivery dates.
//
// GET /v1/shipper/shipment/{orderNumber}/tracking
func (UnimplementedHandler) TrackShipmentByOrderNumber(ctx context.Context, params TrackShipmentByOrderNumberParams) (r TrackShipmentByOrderNumberRes, _ error) {
	return r, ht.ErrNotImplemented
}
