// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AddDataParams is parameters of addData operation.
type AddDataParams struct {
	// The unique identifier of the carrier.
	CarrierId string
}

func unpackAddDataParams(packed middleware.Parameters) (params AddDataParams) {
	{
		key := middleware.ParameterKey{
			Name: "carrierId",
			In:   "path",
		}
		params.CarrierId = packed[key].(string)
	}
	return params
}

func decodeAddDataParams(args [1]string, argsEscaped bool, r *http.Request) (params AddDataParams, _ error) {
	// Decode path: carrierId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "carrierId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CarrierId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "carrierId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// AddTripsParams is parameters of addTrips operation.
type AddTripsParams struct {
	// The unique identifier of the carrier.
	CarrierId string
}

func unpackAddTripsParams(packed middleware.Parameters) (params AddTripsParams) {
	{
		key := middleware.ParameterKey{
			Name: "carrierId",
			In:   "path",
		}
		params.CarrierId = packed[key].(string)
	}
	return params
}

func decodeAddTripsParams(args [1]string, argsEscaped bool, r *http.Request) (params AddTripsParams, _ error) {
	// Decode path: carrierId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "carrierId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CarrierId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "carrierId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CancelShipmentByOrderNumberParams is parameters of cancelShipmentByOrderNumber operation.
type CancelShipmentByOrderNumberParams struct {
	// Order number (5-character alphanumeric code, commonly called PRO number).
	OrderNumber string
}

func unpackCancelShipmentByOrderNumberParams(packed middleware.Parameters) (params CancelShipmentByOrderNumberParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderNumber",
			In:   "path",
		}
		params.OrderNumber = packed[key].(string)
	}
	return params
}

func decodeCancelShipmentByOrderNumberParams(args [1]string, argsEscaped bool, r *http.Request) (params CancelShipmentByOrderNumberParams, _ error) {
	// Decode path: orderNumber.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderNumber",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderNumber = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderNumber",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ConfirmShipmentByOrderNumberParams is parameters of confirmShipmentByOrderNumber operation.
type ConfirmShipmentByOrderNumberParams struct {
	// Order number (5-character alphanumeric code, commonly called PRO number).
	OrderNumber string
}

func unpackConfirmShipmentByOrderNumberParams(packed middleware.Parameters) (params ConfirmShipmentByOrderNumberParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderNumber",
			In:   "path",
		}
		params.OrderNumber = packed[key].(string)
	}
	return params
}

func decodeConfirmShipmentByOrderNumberParams(args [1]string, argsEscaped bool, r *http.Request) (params ConfirmShipmentByOrderNumberParams, _ error) {
	// Decode path: orderNumber.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderNumber",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderNumber = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderNumber",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCarrierApiConfigParams is parameters of getCarrierApiConfig operation.
type GetCarrierApiConfigParams struct {
	// The unique identifier of the carrier.
	CarrierId string
}

func unpackGetCarrierApiConfigParams(packed middleware.Parameters) (params GetCarrierApiConfigParams) {
	{
		key := middleware.ParameterKey{
			Name: "carrierId",
			In:   "path",
		}
		params.CarrierId = packed[key].(string)
	}
	return params
}

func decodeGetCarrierApiConfigParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCarrierApiConfigParams, _ error) {
	// Decode path: carrierId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "carrierId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CarrierId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "carrierId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetDocumentByOrderNumberParams is parameters of getDocumentByOrderNumber operation.
type GetDocumentByOrderNumberParams struct {
	// Order number (5-character alphanumeric code, commonly called PRO number).
	OrderNumber string
	// Type of document to retrieve.
	DocumentType GetDocumentByOrderNumberDocumentType
}

func unpackGetDocumentByOrderNumberParams(packed middleware.Parameters) (params GetDocumentByOrderNumberParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderNumber",
			In:   "path",
		}
		params.OrderNumber = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "documentType",
			In:   "path",
		}
		params.DocumentType = packed[key].(GetDocumentByOrderNumberDocumentType)
	}
	return params
}

func decodeGetDocumentByOrderNumberParams(args [2]string, argsEscaped bool, r *http.Request) (params GetDocumentByOrderNumberParams, _ error) {
	// Decode path: orderNumber.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderNumber",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderNumber = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderNumber",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: documentType.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "documentType",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.DocumentType = GetDocumentByOrderNumberDocumentType(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.DocumentType.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "documentType",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetInvoiceParams is parameters of getInvoice operation.
type GetInvoiceParams struct {
	// Order number (5-character alphanumeric code, commonly called PRO number).
	OrderNumber string
}

func unpackGetInvoiceParams(packed middleware.Parameters) (params GetInvoiceParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderNumber",
			In:   "path",
		}
		params.OrderNumber = packed[key].(string)
	}
	return params
}

func decodeGetInvoiceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetInvoiceParams, _ error) {
	// Decode path: orderNumber.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderNumber",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderNumber = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderNumber",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetJobsParams is parameters of getJobs operation.
type GetJobsParams struct {
	// The unique identifier of the carrier.
	CarrierId string
	// If true, only return currently active jobs.
	ActiveOnly OptBool `json:",omitempty,omitzero"`
	// Filter jobs created after this time (ISO 8601 format).
	StartTime OptDateTime `json:",omitempty,omitzero"`
	// Filter jobs created before this time (ISO 8601 format).
	EndTime OptDateTime `json:",omitempty,omitzero"`
}

func unpackGetJobsParams(packed middleware.Parameters) (params GetJobsParams) {
	{
		key := middleware.ParameterKey{
			Name: "carrierId",
			In:   "path",
		}
		params.CarrierId = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "activeOnly",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ActiveOnly = v.(OptBool)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "startTime",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.StartTime = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "endTime",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EndTime = v.(OptDateTime)
		}
	}
	return params
}

func decodeGetJobsParams(args [1]string, argsEscaped bool, r *http.Request) (params GetJobsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: carrierId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "carrierId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CarrierId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "carrierId",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: activeOnly.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "activeOnly",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotActiveOnlyVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotActiveOnlyVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ActiveOnly.SetTo(paramsDotActiveOnlyVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "activeOnly",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: startTime.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "startTime",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotStartTimeVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotStartTimeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.StartTime.SetTo(paramsDotStartTimeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "startTime",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: endTime.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "endTime",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEndTimeVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotEndTimeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.EndTime.SetTo(paramsDotEndTimeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "endTime",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetQuoteParams is parameters of getQuote operation.
type GetQuoteParams struct {
	// Unique quote ID.
	QuoteId string
}

func unpackGetQuoteParams(packed middleware.Parameters) (params GetQuoteParams) {
	{
		key := middleware.ParameterKey{
			Name: "quoteId",
			In:   "path",
		}
		params.QuoteId = packed[key].(string)
	}
	return params
}

func decodeGetQuoteParams(args [1]string, argsEscaped bool, r *http.Request) (params GetQuoteParams, _ error) {
	// Decode path: quoteId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "quoteId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.QuoteId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "quoteId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetShipmentByOrderNumberParams is parameters of getShipmentByOrderNumber operation.
type GetShipmentByOrderNumberParams struct {
	// Order number (5-character alphanumeric code, commonly called PRO number).
	OrderNumber string
}

func unpackGetShipmentByOrderNumberParams(packed middleware.Parameters) (params GetShipmentByOrderNumberParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderNumber",
			In:   "path",
		}
		params.OrderNumber = packed[key].(string)
	}
	return params
}

func decodeGetShipmentByOrderNumberParams(args [1]string, argsEscaped bool, r *http.Request) (params GetShipmentByOrderNumberParams, _ error) {
	// Decode path: orderNumber.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderNumber",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderNumber = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderNumber",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TrackShipmentByOrderNumberParams is parameters of trackShipmentByOrderNumber operation.
type TrackShipmentByOrderNumberParams struct {
	// Order number (5-character alphanumeric code, commonly called PRO number).
	OrderNumber string
}

func unpackTrackShipmentByOrderNumberParams(packed middleware.Parameters) (params TrackShipmentByOrderNumberParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderNumber",
			In:   "path",
		}
		params.OrderNumber = packed[key].(string)
	}
	return params
}

func decodeTrackShipmentByOrderNumberParams(args [1]string, argsEscaped bool, r *http.Request) (params TrackShipmentByOrderNumberParams, _ error) {
	// Decode path: orderNumber.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "orderNumber",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderNumber = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderNumber",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
