// Code generated by ogen, DO NOT EDIT.
package client

type AddDataRes interface {
	addDataRes()
}

type AddTripsRes interface {
	addTripsRes()
}

type CancelShipmentByOrderNumberRes interface {
	cancelShipmentByOrderNumberRes()
}

type ConfirmShipmentByOrderNumberRes interface {
	confirmShipmentByOrderNumberRes()
}

type CreateShipmentRes interface {
	createShipmentRes()
}

type GetCarrierApiConfigRes interface {
	getCarrierApiConfigRes()
}

type GetDocumentByOrderNumberRes interface {
	getDocumentByOrderNumberRes()
}

type GetInvoiceRes interface {
	getInvoiceRes()
}

type GetJobsRes interface {
	getJobsRes()
}

type GetQuoteRes interface {
	getQuoteRes()
}

type GetShipmentByOrderNumberRes interface {
	getShipmentByOrderNumberRes()
}

type GetTokenRes interface {
	getTokenRes()
}

type RequestQuoteRes interface {
	requestQuoteRes()
}

type TrackShipmentByOrderNumberRes interface {
	trackShipmentByOrderNumberRes()
}
