// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	AddDataOperation                      OperationName = "AddData"
	AddTripsOperation                     OperationName = "AddTrips"
	CancelShipmentByOrderNumberOperation  OperationName = "CancelShipmentByOrderNumber"
	ConfirmShipmentByOrderNumberOperation OperationName = "ConfirmShipmentByOrderNumber"
	CreateShipmentOperation               OperationName = "CreateShipment"
	GetCarrierApiConfigOperation          OperationName = "GetCarrierApiConfig"
	GetDocumentByOrderNumberOperation     OperationName = "GetDocumentByOrderNumber"
	GetInvoiceOperation                   OperationName = "GetInvoice"
	GetJobsOperation                      OperationName = "GetJobs"
	GetQuoteOperation                     OperationName = "GetQuote"
	GetShipmentByOrderNumberOperation     OperationName = "GetShipmentByOrderNumber"
	GetTokenOperation                     OperationName = "GetToken"
	RequestQuoteOperation                 OperationName = "RequestQuote"
	TrackShipmentByOrderNumberOperation   OperationName = "TrackShipmentByOrderNumber"
)
