// Code generated by ogen, DO NOT EDIT.

package client

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *Address) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.DefaultAccessorials.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "defaultAccessorials",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Latitude.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "latitude",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Longitude.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "longitude",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *AddressAccessorialSnapshot) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.CallAheadRequired.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "callAheadRequired",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddressAccessorialSnapshotCallAheadRequired) Validate() error {
	switch s {
	case "HALF_HOUR":
		return nil
	case "ONE_HOUR":
		return nil
	case "TWO_HOURS":
		return nil
	case "START_OF_DAY":
		return nil
	case "DAY_BEFORE":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *AddressAccessorials) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.CallAheadRequired.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "callAheadRequired",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s AddressAccessorialsCallAheadRequired) Validate() error {
	switch s {
	case "HALF_HOUR":
		return nil
	case "ONE_HOUR":
		return nil
	case "TWO_HOURS":
		return nil
	case "START_OF_DAY":
		return nil
	case "DAY_BEFORE":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CancelShipmentByOrderNumberBadRequest) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelShipmentByOrderNumberForbidden) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelShipmentByOrderNumberInternalServerError) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelShipmentByOrderNumberNotFound) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelShipmentByOrderNumberOK) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelShipmentByOrderNumberUnauthorized) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ComponentDetails) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.PoundsWeight.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "poundsWeight",
			Error: err,
		})
	}
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.PalletDimensions {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(elem)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "palletDimensions",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ConfirmShipmentByOrderNumberBadRequest) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ConfirmShipmentByOrderNumberForbidden) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ConfirmShipmentByOrderNumberInternalServerError) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ConfirmShipmentByOrderNumberNotFound) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ConfirmShipmentByOrderNumberOK) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ConfirmShipmentByOrderNumberUnauthorized) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateShipmentBadRequest) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateShipmentForbidden) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateShipmentInternalServerError) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateShipmentOK) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateShipmentUnauthorized) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ExternalAddress) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["[A-Z]{2}"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.State)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "state",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["\\d{5}"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.ZipCode)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "zipCode",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^\\+[1-9]\\d{1,14}$"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.PhoneNumber)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "phoneNumber",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OpenTime.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^([01]?[0-9]|2[0-3]):[0-5][0-9]$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "openTime",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CloseTime.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^([01]?[0-9]|2[0-3]):[0-5][0-9]$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "closeTime",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ExternalCreateShipmentRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.PickupAddress.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "pickupAddress",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.DeliveryAddress.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "deliveryAddress",
			Error: err,
		})
	}
	if err := func() error {
		if s.OrderComponents == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.OrderComponents {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderComponents",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ExternalInvoiceResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Shipper.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "shipper",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Consignee.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "consignee",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.BillTo.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "billTo",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ExternalOrder) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.OrderStatus.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderStatus",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ExternalOrderComponent) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Int{
			MinSet:        true,
			Min:           1,
			MaxSet:        false,
			Max:           0,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    0,
			Pattern:       nil,
		}).Validate(int64(s.PalletCount)); err != nil {
			return errors.Wrap(err, "int")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "palletCount",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{
			MinSet:        true,
			Min:           1,
			MaxSet:        false,
			Max:           0,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    nil,
			Pattern:       nil,
		}).Validate(float64(s.PoundsWeight)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "poundsWeight",
			Error: err,
		})
	}
	if err := func() error {
		if s.PalletDimensions == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "palletDimensions",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ExternalOrderOrderStatus) Validate() error {
	switch s {
	case "INITIALIZED":
		return nil
	case "CONFIRMED":
		return nil
	case "ACCEPTED":
		return nil
	case "ASSIGNED":
		return nil
	case "PICKED_UP":
		return nil
	case "IN_TRANSIT":
		return nil
	case "DELIVERED":
		return nil
	case "CANCELLED":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ExternalRequestQuoteRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.PickupAddress.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "pickupAddress",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.DeliveryAddress.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "deliveryAddress",
			Error: err,
		})
	}
	if err := func() error {
		if s.OrderComponents == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.OrderComponents {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderComponents",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ExternalTracking) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.OrderStatus.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderStatus",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ExternalTrackingOrderStatus) Validate() error {
	switch s {
	case "INITIALIZED":
		return nil
	case "CONFIRMED":
		return nil
	case "ACCEPTED":
		return nil
	case "ASSIGNED":
		return nil
	case "PICKED_UP":
		return nil
	case "IN_TRANSIT":
		return nil
	case "DELIVERED":
		return nil
	case "CANCELLED":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetDocumentByOrderNumberDocumentType) Validate() error {
	switch s {
	case "BILL_OF_LADING":
		return nil
	case "INVOICE":
		return nil
	case "SHIPPING_LABEL":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetInvoiceBadRequest) Validate() error {
	alias := (*ExternalInvoiceResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetInvoiceForbidden) Validate() error {
	alias := (*ExternalInvoiceResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetInvoiceNotFound) Validate() error {
	alias := (*ExternalInvoiceResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetInvoiceOK) Validate() error {
	alias := (*ExternalInvoiceResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetInvoiceUnauthorized) Validate() error {
	alias := (*ExternalInvoiceResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s GetJobsForbiddenApplicationHalJSON) Validate() error {
	alias := ([]OfferWithOrderDataDTO)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetJobsInternalServerErrorApplicationHalJSON) Validate() error {
	alias := ([]OfferWithOrderDataDTO)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetJobsNotFoundApplicationHalJSON) Validate() error {
	alias := ([]OfferWithOrderDataDTO)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetJobsOKApplicationHalJSON) Validate() error {
	alias := ([]OfferWithOrderDataDTO)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetJobsUnauthorizedApplicationHalJSON) Validate() error {
	alias := ([]OfferWithOrderDataDTO)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetShipmentByOrderNumberBadRequest) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentByOrderNumberForbidden) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentByOrderNumberNotFound) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentByOrderNumberOK) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentByOrderNumberUnauthorized) Validate() error {
	alias := (*ExternalOrder)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GpsData) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Float{
			MinSet:        true,
			Min:           -90,
			MaxSet:        true,
			Max:           90,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    nil,
			Pattern:       nil,
		}).Validate(float64(s.Latitude)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "latitude",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Float{
			MinSet:        true,
			Min:           -180,
			MaxSet:        true,
			Max:           180,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    nil,
			Pattern:       nil,
		}).Validate(float64(s.Longitude)); err != nil {
			return errors.Wrap(err, "float")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "longitude",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Int{
			MinSet:        true,
			Min:           0,
			MaxSet:        true,
			Max:           359,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    0,
			Pattern:       nil,
		}).Validate(int64(s.Heading)); err != nil {
			return errors.Wrap(err, "int")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "heading",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.Int{
			MinSet:        true,
			Min:           0,
			MaxSet:        false,
			Max:           0,
			MinExclusive:  false,
			MaxExclusive:  false,
			MultipleOfSet: false,
			MultipleOf:    0,
			Pattern:       nil,
		}).Validate(int64(s.Speed)); err != nil {
			return errors.Wrap(err, "int")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "speed",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *OfferWithOrderDataDTO) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.RouteScore.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "routeScore",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MatchingMethod.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "matchingMethod",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OrderData.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderData",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.PickupAddressData.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "pickupAddressData",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.DropoffAddressData.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "dropoffAddressData",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OrderAccessorials.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderAccessorials",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s OfferWithOrderDataDTOMatchingMethod) Validate() error {
	switch s {
	case "MANUAL":
		return nil
	case "REGION":
		return nil
	case "LANE":
		return nil
	case "TERMINAL":
		return nil
	case "TRIP":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *Order) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.TotalPoundsWeight.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "totalPoundsWeight",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Quote.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "quote",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CancellationReason.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "cancellationReason",
			Error: err,
		})
	}
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.OrderComponents {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderComponents",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *OrderAccessorials) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.PickupAccessorials.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "pickupAccessorials",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.DeliveryAccessorials.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "deliveryAccessorials",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s OrderCancellationReason) Validate() error {
	switch s {
	case "unspecified":
		return nil
	case "customer_cancellation":
		return nil
	case "shipment_entry_error":
		return nil
	case "low_coverage":
		return nil
	case "unacceptable_margin":
		return nil
	case "expired":
		return nil
	case "carrier_exception":
		return nil
	case "shipper_exception":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *Quote) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.TotalWeight.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "totalWeight",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CarrierProbability.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "carrierProbability",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ShipperProbability.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "shipperProbability",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.PickupScoreSurroundingNormalized.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "pickupScoreSurroundingNormalized",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.DropoffScoreSurroundingNormalized.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "dropoffScoreSurroundingNormalized",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Miles.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "miles",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Status.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.QuoteSource.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "quoteSource",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s QuoteQuoteSource) Validate() error {
	switch s {
	case "pricing_model":
		return nil
	case "pricing_model_v2":
		return nil
	case "manual_entry":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s QuoteStatus) Validate() error {
	switch s {
	case "open":
		return nil
	case "display":
		return nil
	case "price_locked":
		return nil
	case "confirmed":
		return nil
	case "rejected":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TrackShipmentByOrderNumberBadRequest) Validate() error {
	alias := (*ExternalTracking)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TrackShipmentByOrderNumberForbidden) Validate() error {
	alias := (*ExternalTracking)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TrackShipmentByOrderNumberNotFound) Validate() error {
	alias := (*ExternalTracking)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TrackShipmentByOrderNumberOK) Validate() error {
	alias := (*ExternalTracking)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TrackShipmentByOrderNumberUnauthorized) Validate() error {
	alias := (*ExternalTracking)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *Trip) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Legs {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "legs",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *TripLeg) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.StartLat.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "startLat",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.StartLong.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "startLong",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.EndLat.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "endLat",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.EndLong.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "endLong",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
